
import ch8.ChainedExceptoinEx;
import ch8.TryWithResourece;

public class Main{
    public static void main(String[] args) throws Exception {
        //InnerEx4.execute();
        ChainedExceptoinEx.execute();
    }

}